language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: "eKYdlW4LMpVQkF095K9d48vvDX3gW2KNXF8qH88sRjyCZqVk5ZBA2T1tA35d5eio6JgWXTKgAtbwsl2DFmmpotMHfv01cdlUoY1EuzSRGoIN07RiG2oFWb5PEzIWKYVYLOPE6ieq8IMd1yPPp/g3Tvl4V8H6a5nyMbMN4HO4qmU="
script:
  - npm run travis
after_success:
  - $(npm bin)/coveralls < ./coverage/lcov.info
